stages:
  - build
  - deploy

variables:
  HELLO_STRING: 'Hello CI/CD!'

merge_notifications:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME =~ /^notification/
  script:
    - cd /root/social-network/back
    - git pull

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Server in fire! Your commit has broken prod..."
