server:
  port: ${SN_ACCOUNT_PORT}
database:
  username: ${SN_DB_USER}
  password: ${SN_DB_PASSWORD}
  url: jdbc:postgresql://${SN_DB_HOST}:${SN_DB_PORT}/${SN_DB_NAME}


jwt:
  secret: ${JWT_SIGNATURE}
spring:
  security:
    filter:
      order: 10
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/dbchangelog-master.xml

email:
  passwordRecovery:
    subject: восстановление пароля
    url: "http://${SN_ACCOUNT_HOST}/change-password/"
  passwordChange:
    subject: изменение пароля
    url: "http://${SN_ACCOUNT_HOST}/shift-password"
  emailChange:
    subject: изменение почтового адреса
    url: "http://${SN_ACCOUNT_HOST}/shift-email"


delete-hash:
  delay-ms: 60000

user:
  hash-expiry-min: 15




